INSERT INTO TB_SERVICO(DESCRICAO, VALOR) VALUES('Corte simples', 20.0);
INSERT INTO TB_SERVICO(DESCRICAO, VALOR) VALUES ('Corte simples com barba', 30.0);
INSERT INTO TB_SERVICO(DESCRICAO, VALOR) VALUES ('Barba', 10.0);
INSERT INTO TB_SERVICO(DESCRICAO, VALOR) VALUES ('Combo', 50.0);

INSERT INTO TB_AGENDAMENTO(DATA, HORARIO) VALUES (TIMESTAMP WITH TIME ZONE '2020-07-13', '08:00 as 08:20');
INSERT INTO TB_AGENDAMENTO(DATA, HORARIO) VALUES (TIMESTAMP WITH TIME ZONE '2020-07-13', '08:00 as 08:20');

INSERT INTO TB_ITEM_PEDIDO(AGENDAMENTO_ID, SERVICO_ID, QUANTIDADE, PRECO) VALUES (1, 1, 2, 20.0);
INSERT INTO TB_ITEM_PEDIDO(AGENDAMENTO_ID, SERVICO_ID, QUANTIDADE, PRECO) VALUES (1, 2, 2, 30.0);
